package aicrimport

import (
	"encoding/json"
	"os"
	"path/filepath"
	"strings"
	"testing"

	aiv1 "github.com/SUSE/aif-operator/api/v1alpha1"
)

const gpuOperator = "gpu-operator"

const recipeYAML = `kind: RecipeResult
criteria:
  service: rke2
  os: sles
  intent: training
metadata:
  version: v1.2.3
componentRefs:
  - name: cert-manager
    namespace: cert-manager
  - name: nfd
    namespace: node-feature-discovery
  - name: gpu-operator
    namespace: gpu-operator
    dependencyRefs: [nfd, cert-manager]
  - name: nvsentinel
    namespace: nvsentinel
    dependencyRefs: [gpu-operator]
`

type folderSpec struct {
	dir, env, values, clusterValues string
	local                           bool
}

func writeBundle(t *testing.T, folders []folderSpec) string {
	t.Helper()
	dir := t.TempDir()
	must(t, os.WriteFile(filepath.Join(dir, "recipe.yaml"), []byte(recipeYAML), 0o644))
	for _, f := range folders {
		p := filepath.Join(dir, f.dir)
		must(t, os.MkdirAll(p, 0o755))
		if f.local {
			must(t, os.WriteFile(filepath.Join(p, "Chart.yaml"), []byte("name: x\n"), 0o644))
			continue
		}
		must(t, os.WriteFile(filepath.Join(p, "upstream.env"), []byte(f.env), 0o644))
		must(t, os.WriteFile(filepath.Join(p, "values.yaml"), []byte("# Generated by AICR\n---\n"+f.values), 0o644))
		if f.clusterValues != "" {
			must(t, os.WriteFile(filepath.Join(p, "cluster-values.yaml"), []byte(f.clusterValues), 0o644))
		}
	}
	return dir
}

func must(t *testing.T, err error) {
	t.Helper()
	if err != nil {
		t.Fatal(err)
	}
}

var fullBundle = []folderSpec{
	{dir: "001-cert-manager", env: "CHART='cert-manager'\nREPO='https://charts.jetstack.io'\nVERSION='v1.17.2'\n", values: "crds:\n  enabled: true\n"},
	{dir: "002-nfd", env: "CHART='node-feature-discovery'\nREPO='https://kubernetes-sigs.github.io/node-feature-discovery/charts'\nVERSION='0.18.3'\n", values: "{}\n"},
	{dir: "003-gpu-operator", env: "CHART='gpu-operator'\nREPO='https://helm.ngc.nvidia.com/nvidia'\nVERSION='v26.7.1'\n",
		values: "nfd:\n  enabled: false\ndriver:\n  version: \"595\"\n  usePrecompiled: true\n", clusterValues: "driver:\n  usePrecompiled: false\n"},
	{dir: "004-nvsentinel", env: "CHART='oci://ghcr.io/nvidia/nvsentinel'\nREPO=''\nVERSION='v1.25.0'\n", values: "labeler:\n  enabled: true\n"},
}

func opts() Options {
	return Options{Name: "nvidia-gpu", DisplayName: "NVIDIA GPU", Version: "1.0.0", Catalog: "nvidia-aicr", CatalogDisplayName: "NVIDIA AICR"}
}

func plan(t *testing.T, folders []folderSpec, o Options) (*Result, error) {
	t.Helper()
	b, err := ReadBundle(writeBundle(t, folders))
	if err != nil {
		t.Fatalf("ReadBundle: %v", err)
	}
	return Plan(b, o)
}

func values(t *testing.T, c aiv1.BlueprintComponent) map[string]any {
	t.Helper()
	var v map[string]any
	if c.Values != nil {
		must(t, json.Unmarshal(c.Values.Raw, &v))
	}
	return v
}

func TestPlanTiersFollowDependencyRefs(t *testing.T) {
	res, err := plan(t, fullBundle, opts())
	if err != nil {
		t.Fatal(err)
	}
	got := make([]string, 0, len(res.Blueprints))
	for _, bp := range res.Blueprints {
		var names []string
		for _, c := range bp.Spec.Components {
			names = append(names, c.ReleaseName)
		}
		got = append(got, bp.Labels[aiv1.BlueprintNameLabel]+"="+strings.Join(names, ","))
	}
	want := []string{"nvidia-gpu-tier1=cert-manager,nfd", "nvidia-gpu-tier2=gpu-operator", "nvidia-gpu-tier3=nvsentinel"}
	if strings.Join(got, " ") != strings.Join(want, " ") {
		t.Errorf("tiers = %v, want %v", got, want)
	}
	if n := len(res.Catalog.Spec.Blueprints); n != 3 {
		t.Errorf("catalog members = %d, want 3", n)
	}
	for _, bp := range res.Blueprints {
		if bp.Labels[aiv1.BlueprintCatalogLabel] != "nvidia-aicr" || bp.Spec.Source != aiv1.BlueprintOriginNvidia {
			t.Errorf("%s: catalog label/source = %q/%q", bp.Name, bp.Labels[aiv1.BlueprintCatalogLabel], bp.Spec.Source)
		}
	}
	if res.Blueprints[1].Name != "nvidia-gpu-tier2-1-0-0" {
		t.Errorf("object name = %q", res.Blueprints[1].Name)
	}
}

func TestPlanComponentMapping(t *testing.T) {
	res, err := plan(t, fullBundle, opts())
	if err != nil {
		t.Fatal(err)
	}
	gpu := res.Blueprints[1].Spec.Components[0]
	if gpu.ChartName != gpuOperator || gpu.ChartVersion != "v26.7.1" || gpu.TargetNamespace != gpuOperator ||
		gpu.ReleaseName != gpuOperator {
		t.Errorf("gpu-operator component = %+v", gpu)
	}
	if gpu.Vendor != "" {
		t.Errorf("vendor = %q, want unset so AI Factory leaves values untouched", gpu.Vendor)
	}
	driver := values(t, gpu)["driver"].(map[string]any)
	if driver["usePrecompiled"] != false || driver["version"] != "595" {
		t.Errorf("cluster-values not merged over values: %v", driver)
	}

	nvs := res.Blueprints[2].Spec.Components[0]
	if nvs.ChartName != "nvsentinel" || nvs.ChartRepo != "aicr-ghcr-io-nvidia" {
		t.Errorf("OCI component chart/repo = %q/%q", nvs.ChartName, nvs.ChartRepo)
	}
	byName := map[string]aiv1.CustomRepoSpec{}
	for _, r := range res.CustomRepos {
		byName[r.Name] = r
	}
	if r := byName["aicr-ghcr-io-nvidia"]; r.Type != "oci" || r.URL != "oci://ghcr.io/nvidia" {
		t.Errorf("OCI repo = %+v", r)
	}
	if r := byName["aicr-helm-ngc-nvidia-com-nvidia"]; r.Type != "helm" || r.URL != "https://helm.ngc.nvidia.com/nvidia" {
		t.Errorf("helm repo = %+v", r)
	}
}

func TestPlanRepoReuse(t *testing.T) {
	o := opts()
	o.RepoNames = map[string]string{"https://helm.ngc.nvidia.com/nvidia/": "nvidia"}
	res, err := plan(t, fullBundle, o)
	if err != nil {
		t.Fatal(err)
	}
	if got := res.Blueprints[1].Spec.Components[0].ChartRepo; got != "nvidia" {
		t.Errorf("chartRepo = %q, want reused %q", got, "nvidia")
	}
	for _, r := range res.CustomRepos {
		if r.URL == "https://helm.ngc.nvidia.com/nvidia" {
			t.Errorf("reused source still declared as custom repo %q", r.Name)
		}
	}
}

func TestPlanCompanionRuleEnablesNFD(t *testing.T) {
	o := opts()
	o.Only = []string{"gpu-operator"}
	res, err := plan(t, fullBundle, o)
	if err != nil {
		t.Fatal(err)
	}
	nfd := values(t, res.Blueprints[0].Spec.Components[0])["nfd"].(map[string]any)
	if nfd["enabled"] != true || len(res.Warnings) != 1 {
		t.Errorf("nfd = %v, warnings = %v; want nfd.enabled=true and one warning", nfd, res.Warnings)
	}

	o.Only = []string{"gpu-operator", "nfd"}
	res, err = plan(t, fullBundle, o)
	if err != nil {
		t.Fatal(err)
	}
	if len(res.Warnings) != 0 {
		t.Errorf("warnings with nfd exported = %v, want none", res.Warnings)
	}
}

func TestPlanRejects(t *testing.T) {
	withLocal := append(append([]folderSpec{}, fullBundle...), folderSpec{dir: "005-gpu-operator-post", local: true})
	single := opts()
	single.Single = true
	unknown := opts()
	unknown.Only = []string{"missing"}
	badName := opts()
	badName.Name = "Not_Valid"
	reserved := opts()
	reserved.Catalog = aiv1.BlueprintCatalogDefault

	tests := []struct {
		name    string
		folders []folderSpec
		opts    Options
		want    string
	}{
		{"local chart", withLocal, opts(), "local charts"},
		{"single across levels", fullBundle, single, "dependency levels"},
		{"unknown --only", fullBundle, unknown, "not in the bundle"},
		{"invalid name", fullBundle, badName, "--name"},
		{"reserved catalog", fullBundle, reserved, "reserved"},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			_, err := plan(t, tt.folders, tt.opts)
			if err == nil || !strings.Contains(err.Error(), tt.want) {
				t.Errorf("Plan() error = %v, want containing %q", err, tt.want)
			}
		})
	}
}

func TestPlanSingleWithinOneLevel(t *testing.T) {
	o := opts()
	o.Single, o.Only = true, []string{"cert-manager", "nfd"}
	res, err := plan(t, fullBundle, o)
	if err != nil {
		t.Fatal(err)
	}
	if len(res.Blueprints) != 1 || res.Blueprints[0].Labels[aiv1.BlueprintNameLabel] != "nvidia-gpu" {
		t.Errorf("blueprints = %d (%v), want one untiered blueprint", len(res.Blueprints), res.Blueprints[0].Labels)
	}
}

func TestWriteLayout(t *testing.T) {
	res, err := plan(t, fullBundle, opts())
	if err != nil {
		t.Fatal(err)
	}
	out := t.TempDir()
	must(t, Write(res, out))
	for _, p := range []string{"blueprints/catalog.yaml", "blueprints/nvidia-gpu-tier1-1-0-0.yaml", "settings-customrepos.yaml", "README.md"} {
		data, err := os.ReadFile(filepath.Join(out, p))
		if err != nil {
			t.Fatalf("missing %s: %v", p, err)
		}
		if strings.Contains(string(data), "status: {}") || strings.Contains(string(data), "creationTimestamp") {
			t.Errorf("%s carries empty status/creationTimestamp", p)
		}
	}
}
