package aicrimport

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"sigs.k8s.io/yaml"
)

// Write lays the result out as an AI Factory git catalog under dir:
//
//	blueprints/catalog.yaml          BlueprintCatalog
//	blueprints/<name>.yaml           one Blueprint per file
//	settings-customrepos.yaml        Settings.spec.customRepos entries
//	README.md                        registration and install order
func Write(res *Result, dir string) error {
	bpDir := filepath.Join(dir, "blueprints")
	if err := os.MkdirAll(bpDir, 0o755); err != nil {
		return err
	}
	if err := writeYAML(filepath.Join(bpDir, "catalog.yaml"), res.Catalog); err != nil {
		return err
	}
	for _, bp := range res.Blueprints {
		if err := writeYAML(filepath.Join(bpDir, bp.Name+".yaml"), bp); err != nil {
			return err
		}
	}
	if err := writeYAML(filepath.Join(dir, "settings-customrepos.yaml"),
		map[string]any{"customRepos": res.CustomRepos}); err != nil {
		return err
	}
	return os.WriteFile(filepath.Join(dir, "README.md"), []byte(readme(res)), 0o644)
}

func writeYAML(path string, obj any) error {
	data, err := yaml.Marshal(obj)
	if err != nil {
		return fmt.Errorf("encode %s: %w", filepath.Base(path), err)
	}
	// Drop the empty status/creationTimestamp the API types marshal by default.
	data = []byte(strings.ReplaceAll(string(data), "  creationTimestamp: null\n", ""))
	data = []byte(strings.TrimSuffix(strings.ReplaceAll(string(data), "\nstatus: {}\n", "\n"), "status: {}\n"))
	return os.WriteFile(path, data, 0o644)
}

func readme(res *Result) string {
	var sb strings.Builder
	sb.WriteString("# NVIDIA AICR blueprint catalog\n\nGenerated by `aicr-import` from an NVIDIA AI Cluster Runtime bundle.\n\n")
	sb.WriteString("## Register\n\n1. Add the entries in `settings-customrepos.yaml` to the AI Factory Settings `spec.customRepos`.\n")
	sb.WriteString("2. Push this directory to a git repository and add it to Settings `spec.blueprintCatalogs`:\n\n")
	fmt.Fprintf(&sb, "```yaml\nblueprintCatalogs:\n  - name: %s\n    repoURL: <git url>\n    branch: main\n    paths: [blueprints]\n```\n\n", res.Catalog.Name)
	sb.WriteString("## Install order\n\nAI Factory installs a blueprint's components concurrently. Install the blueprints in this order, waiting for each workload to reach `Running`:\n\n")
	for i, bp := range res.Blueprints {
		var names []string
		for _, c := range bp.Spec.Components {
			names = append(names, c.ReleaseName)
		}
		fmt.Fprintf(&sb, "%d. `%s`: %s\n", i+1, bp.Labels["ai-factory.suse.com/blueprint-name"], strings.Join(names, ", "))
	}
	sb.WriteString("\nInstalling over an existing release of the same name adopts and upgrades it. Deleting a workload uninstalls every release it owns.\n")
	if len(res.Warnings) > 0 {
		sb.WriteString("\n## Adjustments\n\n")
		for _, w := range res.Warnings {
			fmt.Fprintf(&sb, "- %s\n", w)
		}
	}
	return sb.String()
}
