image:
  repository: registry.suse.com/ai/containers/nvidia/llama-3-8b-instruct
  tag: latest
  pullPolicy: IfNotPresent

replicaCount: 1

service:
  port: 8000
  type: ClusterIP

gpu:
  enabled: true
  count: "1"
  type: nvidia.com/gpu

resources:
  requests:
    cpu: "8"
    memory: "32Gi"
  limits:
    cpu: "8"
    memory: "32Gi"
    nvidia.com/gpu: "1"

tolerations:
  - key: nvidia.com/gpu
    operator: Exists
    effect: NoSchedule

nodeSelector:
  nvidia.com/gpu.present: "true"

imagePullSecrets:
  - name: suse-registry-creds

securityContext:
  runAsNonRoot: true
  runAsUser: 1000

env: []
