apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "generic-container.fullname" . }}
  labels:
    {{- include "generic-container.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "generic-container.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "generic-container.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: container
          image: {{ .Values.image }}
          {{- if .Values.ports }}
          ports:
            {{- toYaml .Values.ports | nindent 12 }}
          {{- end }}
          {{- if .Values.env }}
          env:
            {{- toYaml .Values.env | nindent 12 }}
          {{- end }}
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if .Values.gpu.enabled }}
          resources:
            requests:
              {{- toYaml .Values.resources.requests | nindent 14 }}
            limits:
              {{- toYaml .Values.resources.limits | nindent 14 }}
              {{ .Values.gpu.type }}: {{ .Values.gpu.count | quote }}
          {{- else }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- end }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
