apiVersion: ai.suse.com/v1alpha1
kind: Blueprint
metadata:
  name: smoke-blueprint.0.1.0
spec:
  blueprintName: smoke-blueprint
  version: 0.1.0
  source:
    type: PublishedFromBundle
    publishedFrom:
      bundleNamespace: default
      bundleName: smoke
      bundleGeneration: 1
  components:
    - name: dummy
      repo: oci://example.com/charts
      chart: demo
      version: 0.1.0
  publishedAt: "2026-05-05T00:00:00Z"
  publishedBy: smoke-test
