apiVersion: ai.suse.com/v1alpha1
kind: Workload
metadata:
  namespace: default
  name: smoke
spec:
  name: smoke
  source:
    kind: BundleTest
    bundleTest:
      namespace: default
      name: smoke
      generation: 1
  targetClusters:
    - local
  deployStrategy: helm
