apiVersion: v1
kind: Service
metadata:
  name: {{ include "aif-operator.fullname" . }}
  labels:
    {{- include "aif-operator.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.ports.api }}
      targetPort: api
      protocol: TCP
      name: api
    - port: {{ .Values.service.ports.health }}
      targetPort: health
      protocol: TCP
      name: health
    {{- if .Values.metrics.enabled }}
    - port: {{ .Values.service.ports.metrics }}
      targetPort: metrics
      protocol: TCP
      name: metrics
    {{- end }}
    {{- if .Values.webhook.enabled }}
    - port: {{ .Values.service.ports.webhook }}
      targetPort: webhook
      protocol: TCP
      name: webhook
    {{- end }}
  selector:
    {{- include "aif-operator.selectorLabels" . | nindent 4 }}
